[theme]
primaryColor             = "#1C2F6E"
backgroundColor          = "#F4F6FB"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#1C2F6E"
font                     = "sans serif"

[server]
maxUploadSize = 50
enableCORS    = false

[browser]
gatherUsageStats = false
